version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://mongo:27017/ipssi_mern_group
    depends_on:
      - mongo
    networks:
      - mon-network

  mongo-express:
  image: mongo-express:latest
  container_name: my-mongo-express
  ports:
    - '8081:8081'
  environment:
    - ME_CONFIG_BASICAUTH_USERNAME=user
    - ME_CONFIG_BASICAUTH_PASSWORD=user
    - ME_CONFIG_MONGODB_SERVER=mongodb
  depends_on:
    - mongodb

networks:
  mon-network
